### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'url.txt'报错咨询

### ISSUE THREAD

**Issue by AA1HSHH** [Yolumia/NJUPT-NETWORK#3]
执行`校园网助手post专用版.py`出现报错，这个url.txt里边应该放什么内容呢？报错信息如下

Traceback (most recent call last):
  File "d:/BrowserDownload/byMonth/2024-01/NJUPT-NETWORK-main/NJUPT-NETWORK-main/校园网助手post专用版.py", line 60, in <module>
    url = read_user_inf()
  File "d:/BrowserDownload/byMonth/2024-01/NJUPT-NETWORK-main/NJUPT-NETWORK-main/校园网助手post专用版.py", line 27, in read_user_inf
    with open('url.txt', encoding='utf-8') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'url.txt'

**Comment by Yolumia** [comment]
这个是从url.txt中读取url，可以看新版的代码
